apiVersion: v1
kind: Template
metadata:
  name: http-stub
objects:
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    name: ${INSTANCE_NAME}
  spec:
    minAvailable: 1
    selector:
      matchLabels:
        app: ${INSTANCE_NAME}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ${INSTANCE_NAME}
    name: ${INSTANCE_NAME}
  spec:
    replicas: ${{REPLICAS}}
    selector:
      matchLabels:
        app: ${INSTANCE_NAME}
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    template:
      metadata:
        labels:
          app: ${INSTANCE_NAME}
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - ${INSTANCE_NAME}
                  topologyKey: kubernetes.io/hostname
                weight: 90
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - ${INSTANCE_NAME}
                  topologyKey: topology.kubernetes.io/zone
                weight: 100
        serviceAccountName: ${SERVICE_ACCOUNT}
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: http-stub
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: INSTANCE_NAME
            value: ${INSTANCE_NAME}
          resources:
            requests:
              memory: ${MEMORY_REQUESTS}
              cpu: ${CPU_REQUESTS}
            limits:
              memory: ${MEMORY_LIMIT}
              cpu: ${CPU_LIMIT}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${INSTANCE_NAME}
    name: ${INSTANCE_NAME}
  spec:
    selector:
      app: ${INSTANCE_NAME}
    ports:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 8080
    type: ClusterIP
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${SERVICE_ACCOUNT}
  imagePullSecrets:
  - name: ${IMAGE_PULL_SECRET}
parameters:
- name: IMAGE
  value: quay.io/app-sre/http-stub
- name: IMAGE_TAG
  value: latest
- name: REPLICAS
  value: "3"
- name: INSTANCE_NAME
  value: example
- name: MEMORY_REQUESTS
  value: 150Mi
- name: MEMORY_LIMIT
  value: 150Mi
- name: CPU_REQUESTS
  value: 100m
- name: CPU_LIMIT
  value: 200m
- name: SERVICE_ACCOUNT
  value: "http-stub"
  deplayName: http-stub service account
